package com.ght.problem.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class appData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("problem")
	private com.ght.problem.management.problem problem;

	@org.kie.api.definition.type.Label("managerStatus")
	private java.lang.Boolean managerStatus;

	@org.kie.api.definition.type.Label("solutionApproved")
	private java.lang.Boolean solutionApproved;

	@org.kie.api.definition.type.Label("instanceStatus")
	private java.lang.String instanceStatus;

	@org.kie.api.definition.type.Label("availableSolutions")
	private java.util.List<java.lang.String> availableSolutions;

	@org.kie.api.definition.type.Label("selectedSolution")
	private java.lang.String selectedSolution;

	@org.kie.api.definition.type.Label("creationNote")
	private java.lang.String creationNote;

	@org.kie.api.definition.type.Label("problemManagerNote")
	private java.lang.String problemManagerNote;

	@org.kie.api.definition.type.Label("problemReviewNote")
	private java.lang.String problemReviewNote;

	@org.kie.api.definition.type.Label("reviewAndConfirmNote")
	private java.lang.String reviewAndConfirmNote;

	@org.kie.api.definition.type.Label("investigationAndDiagnosisNote")
	private java.lang.String investigationAndDiagnosisNote;

	@org.kie.api.definition.type.Label("solutionEvaluationNote")
	private java.lang.String solutionEvaluationNote;

	@org.kie.api.definition.type.Label("solutionConfirmationNote")
	private java.lang.String solutionConfirmationNote;

	@org.kie.api.definition.type.Label("rootCauseAnalysisNote")
	private java.lang.String rootCauseAnalysisNote;

	@org.kie.api.definition.type.Label("solutionApplyNote")
	private java.lang.String solutionApplyNote;

	@org.kie.api.definition.type.Label("ProblemRootCause")
	private java.lang.String problemRootCause;

	@org.kie.api.definition.type.Label("problemTasks")
	private java.util.List<com.ght.problem.management.problemTask> problemTasks;

	@org.kie.api.definition.type.Label(value = "assignToTech1")
	private java.lang.String assignToTech1;

	@org.kie.api.definition.type.Label(value = "assignToTech2")
	private java.lang.String assignToTech2;

	public appData() {
	}

	public com.ght.problem.management.problem getProblem() {
		return this.problem;
	}

	public void setProblem(com.ght.problem.management.problem problem) {
		this.problem = problem;
	}

	public java.lang.Boolean getManagerStatus() {
		return this.managerStatus;
	}

	public void setManagerStatus(java.lang.Boolean managerStatus) {
		this.managerStatus = managerStatus;
	}

	public java.lang.Boolean getSolutionApproved() {
		return this.solutionApproved;
	}

	public void setSolutionApproved(java.lang.Boolean solutionApproved) {
		this.solutionApproved = solutionApproved;
	}

	public java.lang.String getInstanceStatus() {
		return this.instanceStatus;
	}

	public void setInstanceStatus(java.lang.String instanceStatus) {
		this.instanceStatus = instanceStatus;
	}

	public java.util.List<java.lang.String> getAvailableSolutions() {
		return this.availableSolutions;
	}

	public void setAvailableSolutions(
			java.util.List<java.lang.String> availableSolutions) {
		this.availableSolutions = availableSolutions;
	}

	public java.lang.String getSelectedSolution() {
		return this.selectedSolution;
	}

	public void setSelectedSolution(java.lang.String selectedSolution) {
		this.selectedSolution = selectedSolution;
	}

	public java.lang.String getCreationNote() {
		return this.creationNote;
	}

	public void setCreationNote(java.lang.String creationNote) {
		this.creationNote = creationNote;
	}

	public java.lang.String getProblemManagerNote() {
		return this.problemManagerNote;
	}

	public void setProblemManagerNote(java.lang.String problemManagerNote) {
		this.problemManagerNote = problemManagerNote;
	}

	public java.lang.String getProblemReviewNote() {
		return this.problemReviewNote;
	}

	public void setProblemReviewNote(java.lang.String problemReviewNote) {
		this.problemReviewNote = problemReviewNote;
	}

	public java.lang.String getReviewAndConfirmNote() {
		return this.reviewAndConfirmNote;
	}

	public void setReviewAndConfirmNote(java.lang.String reviewAndConfirmNote) {
		this.reviewAndConfirmNote = reviewAndConfirmNote;
	}

	public java.lang.String getInvestigationAndDiagnosisNote() {
		return this.investigationAndDiagnosisNote;
	}

	public void setInvestigationAndDiagnosisNote(
			java.lang.String investigationAndDiagnosisNote) {
		this.investigationAndDiagnosisNote = investigationAndDiagnosisNote;
	}

	public java.lang.String getSolutionEvaluationNote() {
		return this.solutionEvaluationNote;
	}

	public void setSolutionEvaluationNote(
			java.lang.String solutionEvaluationNote) {
		this.solutionEvaluationNote = solutionEvaluationNote;
	}

	public java.lang.String getSolutionConfirmationNote() {
		return this.solutionConfirmationNote;
	}

	public void setSolutionConfirmationNote(
			java.lang.String solutionConfirmationNote) {
		this.solutionConfirmationNote = solutionConfirmationNote;
	}

	public java.lang.String getRootCauseAnalysisNote() {
		return this.rootCauseAnalysisNote;
	}

	public void setRootCauseAnalysisNote(java.lang.String rootCauseAnalysisNote) {
		this.rootCauseAnalysisNote = rootCauseAnalysisNote;
	}

	public java.lang.String getSolutionApplyNote() {
		return this.solutionApplyNote;
	}

	public void setSolutionApplyNote(java.lang.String solutionApplyNote) {
		this.solutionApplyNote = solutionApplyNote;
	}

	public java.lang.String getProblemRootCause() {
		return this.problemRootCause;
	}

	public void setProblemRootCause(java.lang.String problemRootCause) {
		this.problemRootCause = problemRootCause;
	}

	public java.util.List<com.ght.problem.management.problemTask> getProblemTasks() {
		return this.problemTasks;
	}

	public void setProblemTasks(
			java.util.List<com.ght.problem.management.problemTask> problemTasks) {
		this.problemTasks = problemTasks;
	}

	public java.lang.String getAssignToTech1() {
		return this.assignToTech1;
	}

	public void setAssignToTech1(java.lang.String assignToTech1) {
		this.assignToTech1 = assignToTech1;
	}

	public java.lang.String getAssignToTech2() {
		return this.assignToTech2;
	}

	public void setAssignToTech2(java.lang.String assignToTech2) {
		this.assignToTech2 = assignToTech2;
	}

	public appData(
			com.ght.problem.management.problem problem,
			java.lang.Boolean managerStatus,
			java.lang.Boolean solutionApproved,
			java.lang.String instanceStatus,
			java.util.List<java.lang.String> availableSolutions,
			java.lang.String selectedSolution,
			java.lang.String creationNote,
			java.lang.String problemManagerNote,
			java.lang.String problemReviewNote,
			java.lang.String reviewAndConfirmNote,
			java.lang.String investigationAndDiagnosisNote,
			java.lang.String solutionEvaluationNote,
			java.lang.String solutionConfirmationNote,
			java.lang.String rootCauseAnalysisNote,
			java.lang.String solutionApplyNote,
			java.lang.String problemRootCause,
			java.util.List<com.ght.problem.management.problemTask> problemTasks,
			java.lang.String assignToTech1, java.lang.String assignToTech2) {
		this.problem = problem;
		this.managerStatus = managerStatus;
		this.solutionApproved = solutionApproved;
		this.instanceStatus = instanceStatus;
		this.availableSolutions = availableSolutions;
		this.selectedSolution = selectedSolution;
		this.creationNote = creationNote;
		this.problemManagerNote = problemManagerNote;
		this.problemReviewNote = problemReviewNote;
		this.reviewAndConfirmNote = reviewAndConfirmNote;
		this.investigationAndDiagnosisNote = investigationAndDiagnosisNote;
		this.solutionEvaluationNote = solutionEvaluationNote;
		this.solutionConfirmationNote = solutionConfirmationNote;
		this.rootCauseAnalysisNote = rootCauseAnalysisNote;
		this.solutionApplyNote = solutionApplyNote;
		this.problemRootCause = problemRootCause;
		this.problemTasks = problemTasks;
		this.assignToTech1 = assignToTech1;
		this.assignToTech2 = assignToTech2;
	}

}