package com.ght.problem.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class problem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("problemNumber")
	private java.lang.String problemNumber;
	@org.kie.api.definition.type.Label("category")
	private java.lang.String category;
	@org.kie.api.definition.type.Label("urgency")
	private java.lang.String urgency;
	@org.kie.api.definition.type.Label("assignmentGroup")
	private java.lang.String assignmentGroup;
	@org.kie.api.definition.type.Label("problemStatement")
	private java.lang.String problemStatement;
	@org.kie.api.definition.type.Label("description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("reportedBy")
	private java.lang.String reportedBy;
	@org.kie.api.definition.type.Label("subGategory")
	private java.lang.String subGategory;
	@org.kie.api.definition.type.Label("priority")
	private java.lang.String priority;
	@org.kie.api.definition.type.Label("assignedTo")
	private java.lang.String assignedTo;
	@org.kie.api.definition.type.Label("state")
	private java.lang.String state;
	@org.kie.api.definition.type.Label("impact")
	private java.lang.String impact;
	@org.kie.api.definition.type.Label("configurationItem")
	private java.lang.String configurationItem;

	public problem() {
	}

	public java.lang.String getProblemNumber() {
		return this.problemNumber;
	}

	public void setProblemNumber(java.lang.String problemNumber) {
		this.problemNumber = problemNumber;
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.String getUrgency() {
		return this.urgency;
	}

	public void setUrgency(java.lang.String urgency) {
		this.urgency = urgency;
	}

	public java.lang.String getAssignmentGroup() {
		return this.assignmentGroup;
	}

	public void setAssignmentGroup(java.lang.String assignmentGroup) {
		this.assignmentGroup = assignmentGroup;
	}

	public java.lang.String getProblemStatement() {
		return this.problemStatement;
	}

	public void setProblemStatement(java.lang.String problemStatement) {
		this.problemStatement = problemStatement;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getReportedBy() {
		return this.reportedBy;
	}

	public void setReportedBy(java.lang.String reportedBy) {
		this.reportedBy = reportedBy;
	}

	public java.lang.String getSubGategory() {
		return this.subGategory;
	}

	public void setSubGategory(java.lang.String subGategory) {
		this.subGategory = subGategory;
	}

	public java.lang.String getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.String priority) {
		this.priority = priority;
	}

	public java.lang.String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(java.lang.String assignedTo) {
		this.assignedTo = assignedTo;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getImpact() {
		return this.impact;
	}

	public void setImpact(java.lang.String impact) {
		this.impact = impact;
	}

	public java.lang.String getConfigurationItem() {
		return this.configurationItem;
	}

	public void setConfigurationItem(java.lang.String configurationItem) {
		this.configurationItem = configurationItem;
	}

	public problem(java.lang.String problemNumber, java.lang.String category,
			java.lang.String urgency, java.lang.String assignmentGroup,
			java.lang.String problemStatement, java.lang.String description,
			java.lang.String reportedBy, java.lang.String subGategory,
			java.lang.String priority, java.lang.String assignedTo,
			java.lang.String state, java.lang.String impact,
			java.lang.String configurationItem) {
		this.problemNumber = problemNumber;
		this.category = category;
		this.urgency = urgency;
		this.assignmentGroup = assignmentGroup;
		this.problemStatement = problemStatement;
		this.description = description;
		this.reportedBy = reportedBy;
		this.subGategory = subGategory;
		this.priority = priority;
		this.assignedTo = assignedTo;
		this.state = state;
		this.impact = impact;
		this.configurationItem = configurationItem;
	}

}