package com.ght.problem.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class rooCause implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "taskNumber")
	private java.lang.String taskNumber;
	@org.kie.api.definition.type.Label(value = "type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label(value = "state")
	private java.lang.String state;
	@org.kie.api.definition.type.Label(value = "priority")
	private java.lang.String priority;
	@org.kie.api.definition.type.Label(value = "dueDate")
	private java.util.Date dueDate;
	@org.kie.api.definition.type.Label(value = "problem")
	private java.lang.String problem;
	@org.kie.api.definition.type.Label(value = "configuraitonItem")
	private java.lang.String configuraitonItem;
	@org.kie.api.definition.type.Label(value = "assignmentGroup")
	private java.lang.String assignmentGroup;
	@org.kie.api.definition.type.Label(value = "assignedTo")
	private java.lang.String assignedTo;
	@org.kie.api.definition.type.Label(value = "shortDescription")
	private java.lang.String shortDescription;
	@org.kie.api.definition.type.Label(value = "description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label(value = "notes")
	private java.lang.String notes;

	public rooCause() {
	}

	public java.lang.String getTaskNumber() {
		return this.taskNumber;
	}

	public void setTaskNumber(java.lang.String taskNumber) {
		this.taskNumber = taskNumber;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.String priority) {
		this.priority = priority;
	}

	public java.util.Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(java.util.Date dueDate) {
		this.dueDate = dueDate;
	}

	public java.lang.String getProblem() {
		return this.problem;
	}

	public void setProblem(java.lang.String problem) {
		this.problem = problem;
	}

	public java.lang.String getConfiguraitonItem() {
		return this.configuraitonItem;
	}

	public void setConfiguraitonItem(java.lang.String configuraitonItem) {
		this.configuraitonItem = configuraitonItem;
	}

	public java.lang.String getAssignmentGroup() {
		return this.assignmentGroup;
	}

	public void setAssignmentGroup(java.lang.String assignmentGroup) {
		this.assignmentGroup = assignmentGroup;
	}

	public java.lang.String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(java.lang.String assignedTo) {
		this.assignedTo = assignedTo;
	}

	public java.lang.String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(java.lang.String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getNotes() {
		return this.notes;
	}

	public void setNotes(java.lang.String notes) {
		this.notes = notes;
	}

	public rooCause(java.lang.String taskNumber, java.lang.String type,
			java.lang.String state, java.lang.String priority,
			java.util.Date dueDate, java.lang.String problem,
			java.lang.String configuraitonItem,
			java.lang.String assignmentGroup, java.lang.String assignedTo,
			java.lang.String shortDescription, java.lang.String description,
			java.lang.String notes) {
		this.taskNumber = taskNumber;
		this.type = type;
		this.state = state;
		this.priority = priority;
		this.dueDate = dueDate;
		this.problem = problem;
		this.configuraitonItem = configuraitonItem;
		this.assignmentGroup = assignmentGroup;
		this.assignedTo = assignedTo;
		this.shortDescription = shortDescription;
		this.description = description;
		this.notes = notes;
	}

}