package com.ght.problem.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class problemTask implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "taskNumber")
	private java.lang.String taskNumber;
	@org.kie.api.definition.type.Label(value = "shortDescription")
	private java.lang.String shortDescription;
	@org.kie.api.definition.type.Label(value = "caller")
	private java.lang.String caller;
	@org.kie.api.definition.type.Label(value = "priority")
	private java.lang.String priority;
	@org.kie.api.definition.type.Label(value = "duDate")
	private java.util.Date duDate;
	@org.kie.api.definition.type.Label(value = "assignTo")
	private java.lang.String assignTo;

	public problemTask() {
	}

	public java.lang.String getTaskNumber() {
		return this.taskNumber;
	}

	public void setTaskNumber(java.lang.String taskNumber) {
		this.taskNumber = taskNumber;
	}

	public java.lang.String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(java.lang.String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public java.lang.String getCaller() {
		return this.caller;
	}

	public void setCaller(java.lang.String caller) {
		this.caller = caller;
	}

	public java.lang.String getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.String priority) {
		this.priority = priority;
	}

	public java.util.Date getDuDate() {
		return this.duDate;
	}

	public void setDuDate(java.util.Date duDate) {
		this.duDate = duDate;
	}

	public java.lang.String getAssignTo() {
		return this.assignTo;
	}

	public void setAssignTo(java.lang.String assignTo) {
		this.assignTo = assignTo;
	}

	public problemTask(java.lang.String taskNumber,
			java.lang.String shortDescription, java.lang.String caller,
			java.lang.String priority, java.util.Date duDate,
			java.lang.String assignTo) {
		this.taskNumber = taskNumber;
		this.shortDescription = shortDescription;
		this.caller = caller;
		this.priority = priority;
		this.duDate = duDate;
		this.assignTo = assignTo;
	}

}